# Site settings
title: Xuan Feng
email: fengxuan@iie.ac.cn
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD candidate at University of Chinese Academy Sicence with research interests in
  network measurement and data-driven security.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://xtalentfeng.github.io" # the base hostname & protocol for your site
twitter_username: 631958057
github_username:  xtalentfeng
# orcid_id: 0000-0003-4072-6263
# google_scholar_id: BNr-fb8AAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "PhD Candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: "https://plus.google.com/u/0/110288225974212014913"
# google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
# bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

plugins:
  - jekyll-sitemap
