# Site settings
title: Xuan Feng
email: Fengxuan@iie.ac.cn
description: > # this means to ignore newlines until "baseurl:"
  I am a Ph.D. candidate at University of Chinese Academy of Sciences. I major in cyber security and my
  research brings a data-driven approach to the study of computer and network security. My work focus on
  defending the Internet’s physical core infrastructure, and guide the design and deployment of widely-used
  physical systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xtalentfeng.github.io" # the base hostname & protocol for your site
#twitter_username: stevenvmiller
github_username:  xtalentfeng

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: ""
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: "https://plus.google.com/u/0/110288225974212014913"
google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

gems:
  - jekyll-sitemap